---
title: "Hello R Markdown"
author: "Frida Gomam"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Background:
The Altman Z Score is


Questions:
[1] How does the Altman Z-Score work?
[2] How much should we remove from the dataset?
[3] Why are these values so skewed? How do we differentiate between values that are skewed+important vs those that just create noise? 




Exploration:


We can see that the data is skewed heavily towards the negative so removing this data is necessary to effecitvely see how the z-score is changing.[2] [3]
```{r zscore}
plotthis <- ZScoreYearsSummaryV3 %>% 
  mutate(Year = substr(ZScoreYearsSummaryV3$DATADATE,1,4)) %>%
  group_by(Year) %>% 
  summarise(mean(Avg_ZScore))

plot(plotthis)

```

Once removing this information we find the following changes: 

```{r zscore}

ZscoreGroupedbyFY <- DataZscore %>% 
  group_by(FYEAR) %>% 
  summarise(Zscore=mean(Zscore))

ggplot(ZscoreGroupedbyFY, aes(x = FYEAR, y = Zscore))+
  geom_line()+
  geom_point()+
  ggtitle('Avg Zscore by Year')


```